# Build the Buildroot and make SDK

name: build

# Triggers the workflow on push or pull request events
on: [ workflow_dispatch, pull_request ]
jobs:
  build-buildroot:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3
          with:
            path: buildroot-rk3588
      
        - name: Write SSH keys and pull submodules
          working-directory: ./buildroot-rk3588
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            host='github.com'
            hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
            ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

        - name: Install depends
          run: sudo apt-get install -y debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git

        - name: Submodules init
          working-directory: ./buildroot-rk3588
          run: |
            pwd
            ls -l
            git submodule init
            git submodule update --recursive
            ls -l 

        - name: Configure Buildroot
          working-directory: ./buildroot-rk3588/buildroot
          run: make BR2_EXTERNAL=../external rock5b_defconfig

        - name: Build Buildroot
          working-directory: ./buildroot-rk3588/buildroot
          run: make -j32

        - name: Run legal-info
          working-directory: ./buildroot-rk3588/buildroot
          run: make legal-info

        - name: Create SDK 
          working-directory: ./buildroot-rk3588/buildroot
          run: make sdk

        - name: Copy artifacts
          working-directory: ./buildroot-rk3588/buildroot
          run: | 
            mkdir ~/artifacts
            cp -v output/images/sdcard.img ~/artifacts
            mkdir ~/sdk
            cp -v output/images/*sdk*.tar.gz ~/sdk

        - name: Upload Artifact GitHub Action
          uses: actions/upload-artifact@v3
          with: 
            name: download-image
            path: ~/artifacts

        - name: Upload SDK GitHub Action
          uses: actions/upload-artifact@v3
          with: 
            name: download-sdk
            path: ~/sdk
