# Build the Buildroot and make SDK

name: build

# Triggers the workflow on push or pull request events
on: 
  workflow_dispatch
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merge
